### PR TITLE
Plug sends up URL error occurred on 

### LINKED ISSUE #51: Plug Broken In 1.7
Using the plug with the new version raises and error:
```
[error] #PID<0.542.0> running RegistrarWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: GET /sadfasdf
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Map.from_struct/1
```

I believe is is associated to this change: https://github.com/fazibear/airbrakex/blob/master/lib/airbrakex/notifier.ex#L39
The plug returns errors as a map already and `Map.from_struct/1` is expecting a struct.

I'll try and put a fix in if I can as I'm already working on putting in tests for the plug (so that I can add URLs to the context with the plug)

### PR DESCRIPTION
**Pull request by aturkewi**
- Fixes issue with plug not sending error to notifier as struct (closes #51 )
- Adds a test for the plug (hopefully we can catch breaking errors ahead of time now :) )
- Sends up URL from the plug (based on #32 )

cc @fazibear

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -4,3 +4,4 @@
 erl_crash.dump
 *.ez
 *.tar
+.tool-versions
```
Comment (aturkewi) [inline .gitignore:7]: This is just for the version manager I use. If you don't want it in here, let me know and I'll get rid of it.

File: lib/airbrakex/notifier.ex [hunk 2]
```diff
@@ -36,11 +36,14 @@ defmodule Airbrakex.Notifier do
   defp add_error(payload, nil), do: payload
 
   defp add_error(payload, error) do
-    error = Map.from_struct(error)
+    error = get_error_as_map(error)
```
Comment (aturkewi) [inline lib/airbrakex/notifier.ex:39]: If this fix is being implemented elsewhere, I can remove it from this PR as well.

**Comment by fazibear** [comment]
Thanks! 🍺
